[workspace]

members = [
  "contract-bindings",
  "contracts/rust",
  "example-l2",
  "gen-bindings",
  "sequencer",
  "utils",
]

# TODO: remove
# Patch Jellyfish until the crypto_kx compatibility issue is fixed
# https://github.com/EspressoSystems/jellyfish/commit/36dceb63aa5b452b9551c0139bc5512d17f780cf
[patch."https://github.com/EspressoSystems/jellyfish"]
jf-primitives = { git = "https://github.com/EspressoSystems//jellyfish", rev = "e6024a7" }
