[workspace]

members = [
  "contract-bindings",
  "contracts/rust",
  "example-l2",
  "gen-bindings",
  "sequencer",
  "utils",
]

[patch."https://github.com/EspressoSystems/jellyfish"]
jf-primitives = { path = "../jellyfish/primitives" }
