[workspace]

resolver = "2"

members = ["contract-bindings", "contracts/rust", "sequencer", "utils"]

[workspace.dependencies]
hotshot = { git = "https://github.com/EspressoSystems/hotshot", rev = "251a3e6bf1e8af1d0af757a6c0ceb836f8ecfef9" }
hotshot-orchestrator = { git = "https://github.com/EspressoSystems/hotshot", rev = "251a3e6bf1e8af1d0af757a6c0ceb836f8ecfef9" }
hotshot-signature-key = { git = "https://github.com/EspressoSystems/hotshot", rev = "251a3e6bf1e8af1d0af757a6c0ceb836f8ecfef9" }
hotshot-types = { git = "https://github.com/EspressoSystems/hotshot", rev = "251a3e6bf1e8af1d0af757a6c0ceb836f8ecfef9" }
hotshot-web-server = { git = "https://github.com/EspressoSystems/hotshot", rev = "251a3e6bf1e8af1d0af757a6c0ceb836f8ecfef9" }
hotshot-testing = { git = "https://github.com/EspressoSystems/hotshot", rev = "251a3e6bf1e8af1d0af757a6c0ceb836f8ecfef9" }

hotshot-query-service = { git = "https://github.com/EspressoSystems/hotshot-query-service", branch = "main" }

jf-plonk = { git = "https://github.com/EspressoSystems/jellyfish", features = [
  "test-apis",
  "test-srs",
] }
jf-primitives = { git = "https://github.com/EspressoSystems/jellyfish", features = [
  "std",
  "test-srs",
] }
jf-relation = { git = "https://github.com/EspressoSystems/jellyfish", features = [
  "std",
] }
jf-utils = { git = "https://github.com/EspressoSystems/jellyfish" }

surf-disco = { git = "https://github.com/EspressoSystems/surf-disco", tag = "v0.4.4" }
tide-disco = { git = "https://github.com/EspressoSystems/tide-disco", tag = "v0.4.4" }

itertools = "0.12"
