[package]
name = "builder"
description = "A standalone builder service"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = { workspace = true }
async-broadcast = "0.7.0"
async-compatibility-layer = { workspace = true }
async-lock = "2.2"
async-std = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true }
cld = { workspace = true }
committable = "0.2"
dotenvy = { workspace = true }
es-version = { workspace = true }
ethers = { workspace = true }
futures = { workspace = true }
hotshot = { workspace = true }
hotshot-builder-api = { git = "https://github.com/EspressoSystems/HotShot.git", tag = "0.5.34" }
hotshot-builder-core = { git = "https://github.com/EspressoSystems/hotshot-builder-core", branch = "abdul/update-deps" }
hotshot-events-service = { workspace = true }
hotshot-orchestrator = { workspace = true }
hotshot-stake-table = { workspace = true }
hotshot-state-prover = { path = "../hotshot-state-prover" }
hotshot-types = { workspace = true }
jf-primitives = { workspace = true }
portpicker = "0.1.1"
rand = "0.8.5"
sequencer = { path = "../sequencer", features = ["testing"] }
serde = { workspace = true }
snafu = { workspace = true }
surf = "2.3.1"
surf-disco = { workspace = true }
tagged-base64 = "0.4"
tide-disco = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
vbs = { workspace = true }
