name: Test Demo Native

on:
  push:
    branches:
      - main
      - release-*
    tags:
      # YYYYMMDD
      - "20[0-9][0-9][0-1][0-9][0-3][0-9]*"
  schedule:
    - cron: "0 0 * * 1"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RUSTFLAGS: '--cfg async_executor_impl="async-std" --cfg async_channel_impl="async-std"'
  RUST_LOG: info,libp2p=off,node=error

jobs:
  demo-native:
    runs-on: ubuntu-latest
    steps:
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install process-compose
        run: |
          sh -c "$(curl --location https://raw.githubusercontent.com/F1bonacc1/process-compose/main/scripts/get-pc.sh)" -- -d
          export PATH=`pwd`/bin:$PATH
          echo "PATH=$PATH" >> "$GITHUB_ENV"
          pwd
          ls `pwd`/bin
          echo "$PATH"
          cat "$GITHUB_ENV"
          which process-compose

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Enable Rust Caching
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --release

      - name: Test Demo
        run: |
          pwd
          echo "$PATH"
          cat "$GITHUB_ENV"
          which process-compose
          scripts/demo-native &
          scripts/smoke-test-demo
          bin/process-compose down
